### ISSUE TITLE
missing hyper params

### ISSUE THREAD

**Issue by vincentwi** [Softcatala/whisper-ctranslate2#112]
Hi, I noticed there are some params here that are not in ctranslate2's implementation for [generate](https://opennmt.net/CTranslate2/python/ctranslate2.models.Whisper.html#ctranslate2.models.Whisper.generate).

Where would I modify these params within ctranslate2? For example, `hallucination_silence_threshold` and `temperature`? 
Is it that the naming convention is different (e.g. `best_of` is `sampling_topk`)? Something like `condition_on_previous_text` could be aliased to `initial_prompt` or `prefix` but I see they are also included the kwargs list. 

```
class TranscriptionOptions(NamedTuple):
    beam_size: int
    best_of: int
    patience: float
    length_penalty: float
    repetition_penalty: float
    no_repeat_ngram_size: int
    log_prob_threshold: Optional[float]
    no_speech_threshold: Optional[float]
    compression_ratio_threshold: Optional[float]
    condition_on_previous_text: bool
    prompt_reset_on_temperature: float
    temperature: List[float]
    initial_prompt: Optional[str]
    prefix: Optional[str]
    hotwords: Optional[str]
    suppress_blank: bool
    suppress_tokens: Optional[List[int]]
    #    max_initial_timestamp: float
    word_timestamps: bool
    print_colors: bool
    prepend_punctuations: str
    append_punctuations: str
    hallucination_silence_threshold: Optional[float]
    vad_filter: bool
    vad_threshold: Optional[float]
    vad_min_speech_duration_ms: Optional[int]
    vad_max_speech_duration_s: Optional[int]
    vad_min_silence_duration_ms: Optional[int]
```

Thank you for you help. If you could direct me to where these are initialized, I can take it from there!

**Comment by jordimas** [comment]
Hello. The goal of the project is:

_Whisper command line client compatible with original OpenAI client based on CTranslate2._

As part of this we used OpenIA command line options, since the goal was for this tool be a drop replacement.

Over time, we added faster-whisper specific options too.

You can type the following to see all the options:

_whisper-ctranslate2 --help_

If you have a feedback on any missing argument missing which you consider important let me know and I will consider adding it. Thanks

**Comment by vincentwi** [comment]
Understood, these are faster-whisper specific options. thank you
